library(googlesheets4)
library(shiny)
library(shinydashboard)
library(DT)
library(dplyr)
library(ggplot2)
library(plotly)
library(shinyWidgets)
library(viridis)
library(RColorBrewer)
library(data.table)
library(readr)
library(knitr)
library(rmarkdown)
library(meta)
library(metafor)
library(metaviz)
library(lubridate)
library(shinycssloaders)
library(aws.s3)
library(magick)
library(stringr)
library(glue)
library(DiagrammeR)
library(httr)
library(xml2)
library(tidyr)
library(purrr)
library(rvest)
library(htmltools)
library(textclean)
library(tinytex)
library(jsonlite)


source('configure.R')

# drugList <- googlesheets4::read_sheet(googleSheetId, sheet = "drugList") 

drugList <- googlesheets4::read_sheet(googleSheetId, sheet = "longlist")[ ,1]%>%
  mutate(Drug = tolower(Drug))
